[project]
name = "net-login"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "playwright>=1.48.0",
    "schedule>=1.2.0",
    "pystray>=0.19.5",
    "pillow>=10.0.0",
]
